version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '04:00'
      timezone: US/Arizona
    open-pull-requests-limit: 6
    assignees:
      - godber
      - jsnoble
    ignore:
      - dependency-name: aws-sdk
        versions:
          - '> 2.885.0'
      - dependency-name: '@types/node'
        versions:
          - '> 14.14.37'
