enableGlobalCache: true

enableProgressBars: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.6.0.cjs

npmAuthToken: "${NODE_AUTH_TOKEN:-placeHolderToken}"

packageExtensions:
  "@typescript-eslint/utils@*":
    dependencies:
      "@types/typescript": "*"
      typescript: "*"
  "@terascope/scripts@*":
    dependencies:
      typescript: "*"
  "@typescript-eslint/tsconfig-utils@*":
    dependencies:
      typescript: "*"
  "ts-jest@*":
    dependencies:
      typescript: "*"
