packages:
  - 'packages/*'
  - 'asset'

blockExoticSubdeps: true

minimumReleaseAge: 1440 # 1 day

minimumReleaseAgeExclude:
  - '@terascope/*'
  - teraslice-client-js
  - teraslice-test-harness

trustPolicy: no-downgrade

trustPolicyExclude:
  - 'semver@6.3.1' # false positive - maintainer change
