// NOTE: This code is auto-generated by `teraslice-cli assets registry`
// any manual changes will be lost next time this gets auto-generated.

import FileExporter from '../src/file_exporter/processor';
import FileExporterSchema from '../src/file_exporter/schema';

import FileReaderFetcher from '../src/file_reader/fetcher';
import FileReaderSchema from '../src/file_reader/schema';
import FileReaderSlicer from '../src/file_reader/slicer';

import FileReaderAPI from '../src/file_reader_api/api';
import FileReaderAPISchema from '../src/file_reader_api/schema';

import FileSenderAPI from '../src/file_sender_api/api';
import FileSenderAPISchema from '../src/file_sender_api/schema';

import S3Exporter from '../src/s3_exporter/processor';
import S3ExporterSchema from '../src/s3_exporter/schema';

import S3ReaderFetcher from '../src/s3_reader/fetcher';
import S3ReaderSchema from '../src/s3_reader/schema';
import S3ReaderSlicer from '../src/s3_reader/slicer';

import S3ReaderAPI from '../src/s3_reader_api/api';
import S3ReaderAPISchema from '../src/s3_reader_api/schema';

import S3SenderAPI from '../src/s3_sender_api/api';
import S3SenderAPISchema from '../src/s3_sender_api/schema';

export const ASSETS = {
    file_exporter: {
        Processor: FileExporter,
        Schema: FileExporterSchema,
    },
    file_reader: {
        Fetcher: FileReaderFetcher,
        Schema: FileReaderSchema,
        Slicer: FileReaderSlicer,
    },
    file_reader_api: {
        API: FileReaderAPI,
        Schema: FileReaderAPISchema,
    },
    file_sender_api: {
        API: FileSenderAPI,
        Schema: FileSenderAPISchema,
    },
    s3_exporter: {
        Processor: S3Exporter,
        Schema: S3ExporterSchema,
    },
    s3_reader: {
        Fetcher: S3ReaderFetcher,
        Schema: S3ReaderSchema,
        Slicer: S3ReaderSlicer,
    },
    s3_reader_api: {
        API: S3ReaderAPI,
        Schema: S3ReaderAPISchema,
    },
    s3_sender_api: {
        API: S3SenderAPI,
        Schema: S3SenderAPISchema,
    },
};
