name: Daily Docker Cache

on:
  schedule:
    - cron: '0 11 * * 1-5' # Monday - Friday at 4am Arizona Time
  workflow_dispatch:

jobs:
  call-refresh-docker-cache-workflow:
    uses: terascope/workflows/.github/workflows/refresh-docker-cache.yml@8c9327b7f1979b72e76dc3eac467bc85b34dbbd2
    secrets: inherit
