name: Daily Docker Cache

on:
  schedule:
    - cron: '0 11 * * 1-5' # Monday - Friday at 4am Arizona Time
  workflow_dispatch:

jobs:
  call-refresh-docker-cache-workflow:
    uses: terascope/workflows/.github/workflows/refresh-docker-cache.yml@2220e2db7c713ea16a8cacbd1f5aef926e77ba5c
    secrets: inherit
